version: '3.8'

services:
  # NestJS Backend service
  nestjs-backend:
    build:
      context: ./NestJSBackend/diet-chart-generator
      dockerfile: Dockerfile
    container_name: diet-chart-nestjs
    env_file:
      - ./NestJSBackend/diet-chart-generator/.env.production
    environment:
      - NODE_ENV=production
      - PYTHON_API_URL=http://python-backend:8000
    ports:
      - "3001:3001"
    networks:
      - diet-chart-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: diet-chart-frontend
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - "3000:3000"
    networks:
      - diet-chart-network
    restart: unless-stopped

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: diet-chart-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - nestjs-backend
    networks:
      - diet-chart-network
    restart: unless-stopped

networks:
  diet-chart-network:
    driver: bridge